version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    environment:
      - REVERB_APP_ID=${REVERB_APP_ID}
      - REVERB_APP_KEY=${REVERB_APP_KEY}
      - REVERB_APP_SECRET=${REVERB_APP_SECRET}
      - REVERB_HOST=${REVERB_HOST}
      - REVERB_PORT=${REVERB_PORT}
      - REVERB_PATH=${REVERB_PATH}
      - REVERB_SCHEME=${REVERB_SCHEME}
      - REVERB_DEBUG=${REVERB_DEBUG}

  reverb:
    image: laravel-app
    container_name: laravel-reverb
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan reverb:start
    networks:
      - laravel
    depends_on:
      - app
    ports:
      - "6001:6001"
    environment:
      - REVERB_APP_ID=${REVERB_APP_ID}
      - REVERB_APP_KEY=${REVERB_APP_KEY}
      - REVERB_APP_SECRET=${REVERB_APP_SECRET}
      - REVERB_HOST=${REVERB_HOST}
      - REVERB_PORT=${REVERB_PORT}
      - REVERB_PATH=${REVERB_PATH}
      - REVERB_SCHEME=${REVERB_SCHEME}
      - REVERB_DEBUG=${REVERB_DEBUG}

  webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel

  db:
    image: postgres:13
    container_name: laravel-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local
